// Auth Dispatch States
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS"
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

// Profile Dispatch States
export const LOAD_USER_PROFILE_SUCCESS = "LOAD_USER_PROFILE_SUCCESS"
export const LOAD_USER_PROFILE_FAIL = "LOAD_USER_PROFILE_FAIL"
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS"
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL"
export const UPDATE_IS_STAFF = "UPDATE_IS_STAFF"

// Comics Dispatch States
export const LOAD_DC_SCRAPED_OMNIS_PB_SUCCESS =
    "LOAD_DC_SCRAPED_OMNIS_PB_SUCCESS"
export const LOAD_DC_SCRAPED_OMNIS_PB_FAIL = "LOAD_DC_SCRAPED_OMNIS_PB_FAIL"
export const LOAD_CHARACTERS_SUCCESS = "LOAD_CHARACTERS_SUCCESS"
export const LOAD_CHARACTERS_FAIL = "LOAD_CHARACTERS_FAIL"
export const LOAD_PUBLISHERS_SUCCESS = "LOAD_PUBLISHERS_SUCCESS"
export const LOAD_PUBLISHERS_FAIL = "LOAD_PUBLISHERS_FAIL"
export const LOAD_BOOKS_SUCCESS = "LOAD_BOOKS_SUCCESS"
export const LOAD_BOOKS_FAIL = "LOAD_BOOKS_FAIL"
