# Generated by Django 4.1 on 2022-09-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(choices=[('DC', 'DC Comics'), ('MA', 'Marvel'), ('IM', 'Image')], default='MA', max_length=2)),
                ('format', models.CharField(choices=[('OM', 'Omnibus'), ('HA', 'Hardcover'), ('TPB', 'Trade Paperback')], default='OM', max_length=3)),
                ('marvel_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=256, null=True)),
                ('author', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Omnibus',
        ),
    ]
