# Generated by Django 4.1 on 2022-09-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_book_delete_omnibus'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(null=True),
        ),
    ]
