# Generated by Django 4.1 on 2025-03-30 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DC', 'DC Comics'), ('MARVEL', 'Marvel'), ('IMAGE', 'Image'), ('BOOM', 'Boom Studios'), ('SKYBOUND', 'Skybound')], default='MARVEL', max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='team',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('OM', 'Omnibus'), ('HC', 'Hardcover'), ('TPB', 'Trade Paperback')], default='OM', max_length=3),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.character'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.publisher'),
        ),
    ]
