# Generated by Django 4.1 on 2025-03-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_publisher_book_page_count_book_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='key',
            field=models.CharField(default='MARVEL', max_length=8),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
