# Generated by Django 4.1 on 2025-03-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_publisher_key_alter_publisher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='uploads/book-thumbnails/'),
        ),
    ]
