# Generated by Django 5.2 on 2026-07-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_alter_book_isbn_alter_book_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='key',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
