# Generated by Django 5.2 on 2026-07-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_remove_publisher_key_alter_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
