# Generated by Django 5.2 on 2026-07-30 14:48
# Hand-edited: a plain AlterField can't convert the existing free-text
# `author` CharField into a ForeignKey — Postgres would try to cast values
# like "Scott Snyder" straight to an integer and fail. Instead this adds a
# new FK column, migrates each book's existing author string into an Author
# row (reusing one row per distinct name), then drops the old column and
# renames the new one into its place.

import django.db.models.deletion
from django.db import migrations, models


def migrate_author_strings_to_fk(apps, schema_editor):
    Book = apps.get_model('mainsite', 'Book')
    Author = apps.get_model('mainsite', 'Author')

    for book in Book.objects.all():
        name = (book.author_old or '').strip()
        if not name:
            continue
        author, _ = Author.objects.get_or_create(name=name)
        book.author_new_id = author.id
        book.save(update_fields=['author_new'])


def migrate_author_fk_to_strings(apps, schema_editor):
    Book = apps.get_model('mainsite', 'Book')

    for book in Book.objects.select_related('author_new').all():
        book.author_old = book.author_new.name if book.author_new else None
        book.save(update_fields=['author_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_alter_publisher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_old',
        ),
        migrations.AddField(
            model_name='book',
            name='author_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.author'),
        ),
        migrations.RunPython(migrate_author_strings_to_fk, migrate_author_fk_to_strings),
        migrations.RemoveField(
            model_name='book',
            name='author_old',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author_new',
            new_name='author',
        ),
    ]
