# Generated by Django 5.2 on 2026-07-30 15:10

from django.db import migrations, models

# Migrate to new field type
def migrate_fk_to_m2m(apps, schema_editor):
    Book = apps.get_model('mainsite', 'Book')

    for book in Book.objects.all():
        if book.author_id:
            book.authors.add(book.author_id)
        if book.character_id:
            book.characters.add(book.character_id)


def migrate_m2m_to_fk(apps, schema_editor):
    Book = apps.get_model('mainsite', 'Book')

    for book in Book.objects.all():
        first_author = book.authors.first()
        first_character = book.characters.first()
        book.author_id = first_author.id if first_author else None
        book.character_id = first_character.id if first_character else None
        book.save(update_fields=['author', 'character'])


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='mainsite.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='characters',
            field=models.ManyToManyField(blank=True, to='mainsite.character'),
        ),
        migrations.RunPython(migrate_fk_to_m2m, migrate_m2m_to_fk),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='character',
        ),
    ]
