# Generated by Django 5.2 on 2026-07-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_remove_book_author_remove_book_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='characters',
            field=models.ManyToManyField(to='mainsite.character'),
        ),
    ]
