# Generated by Django 5.2 on 2026-08-02

import django.db.models.deletion
from django.db import migrations, models


FORMAT_CHOICES = [
    ('OM', 'Omnibus'),
    ('HC', 'Hardcover'),
    ('TPB', 'Trade Paperback'),
]

# Migrate to new field type
def migrate_format_strings_to_fk(apps, schema_editor):
    Book = apps.get_model('mainsite', 'Book')
    Format = apps.get_model('mainsite', 'Format')

    formats_by_abbreviation = {}
    for abbreviation, name in FORMAT_CHOICES:
        fmt, _ = Format.objects.get_or_create(abbreviation=abbreviation, defaults={'name': name})
        formats_by_abbreviation[abbreviation] = fmt

    for book in Book.objects.all():
        abbreviation = (book.format_old or '').strip()
        fmt = formats_by_abbreviation.get(abbreviation)
        if fmt is None:
            continue
        book.format_new_id = fmt.id
        book.save(update_fields=['format_new'])


def migrate_format_fk_to_strings(apps, schema_editor):
    Book = apps.get_model('mainsite', 'Book')

    for book in Book.objects.select_related('format_new').all():
        book.format_old = book.format_new.abbreviation if book.format_new else None
        book.save(update_fields=['format_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_artist_book_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='format',
            new_name='format_old',
        ),
        migrations.AddField(
            model_name='book',
            name='format_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.format'),
        ),
        migrations.RunPython(migrate_format_strings_to_fk, migrate_format_fk_to_strings),
        migrations.RemoveField(
            model_name='book',
            name='format_old',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='format_new',
            new_name='format',
        ),
        migrations.AddField(
            model_name='book',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.subcategory'),
        ),
    ]
