# Generated by Django 5.2 on 2026-08-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_format_subcategory_and_book_format_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='volume_number',
            field=models.IntegerField(null=True),
        ),
    ]
