# Generated by Django 5.2 on 2026-08-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0019_team_alter_book_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='characters',
            field=models.ManyToManyField(blank=True, to='mainsite.character'),
        ),
    ]
