# Generated by Django 5.2 on 2026-08-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0020_alter_team_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='characters',
            field=models.ManyToManyField(blank=True, to='mainsite.character'),
        ),
    ]
