# Generated by Django 5.2 on 2026-08-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0022_alter_artist_options_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='owned_books',
            field=models.ManyToManyField(blank=True, related_name='owned_by', to='mainsite.book'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wishlist_books',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='mainsite.book'),
        ),
    ]
