# Generated by Django 5.2 on 2026-09-18 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0023_userprofile_owned_books_userprofile_wishlist_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainsite.publisher'),
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('name', 'publisher'), name='unique_character_name_per_publisher'),
        ),
    ]
