client_max_body_size 500M;

server {
    server_name  www.omnitrackers.com;
    return       301 https://omnitrackers.com$request_uri;
}

server {
    server_name  dunneweb.com www.dunneweb.com;
    return       301 https://omnitrackers.com/about;
}