# Generated by Django 4.1 on 2025-03-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
